CREATE TABLE [dbo].[T_FUNCTION] (
    [FUNCTION_CODE] VARCHAR (50)  NOT NULL,
    [FUNCTION_DESC] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_T_FUNCTION] PRIMARY KEY CLUSTERED ([FUNCTION_CODE] ASC)
);

