CREATE TABLE [dbo].[T_ROLE_FUNCTION] (
    [ID]            INT          IDENTITY (1, 1) NOT NULL,
    [ROLE_CODE]     VARCHAR (50) NOT NULL,
    [FUNCTION_CODE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_T_ROLE_FUNCTION] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_T_ROLE_FUNCTION_T_FUNCTION] FOREIGN KEY ([FUNCTION_CODE]) REFERENCES [dbo].[T_FUNCTION] ([FUNCTION_CODE]),
    CONSTRAINT [FK_T_ROLE_FUNCTION_T_ROLE] FOREIGN KEY ([ROLE_CODE]) REFERENCES [dbo].[T_ROLE] ([ROLE_CODE])
);

