CREATE TABLE [dbo].[T_USER] (
    [ID]            INT           IDENTITY (1, 1) NOT NULL,
    [USER_ID]       VARCHAR (50)  NOT NULL,
    [USER_NAME]     VARCHAR (500) NOT NULL,
    [USER_PWD]      VARCHAR (500) NOT NULL,
    [GENDER]        VARCHAR (50)  NOT NULL,
    [MOBILE_NUMBER] VARCHAR (8)   NULL,
    [EMAIL_ADDRESS] VARCHAR (250) NULL,
    [GRADE]         VARCHAR (50)  NULL,
    [IS_DELETED]    BIT           CONSTRAINT [DF_T_USER_IS_DELETED] DEFAULT ((0)) NOT NULL,
    [CREATED_BY]    VARCHAR (50)  CONSTRAINT [DF_T_USER_CREATED_BY] DEFAULT ('SYSTEM') NOT NULL,
    [CREATED_DATE]  DATETIME      CONSTRAINT [DF_T_USER_CREATED_DATE] DEFAULT (getdate()) NOT NULL,
    [UPDATED_BY]    VARCHAR (50)  CONSTRAINT [DF_T_USER_UPDATED_BY] DEFAULT ('SYSTEM') NOT NULL,
    [UPDATED_DATE]  DATETIME      CONSTRAINT [DF_T_USER_UPDATED_DATE] DEFAULT (getdate()) NOT NULL,
    [TIME_STAMP]    ROWVERSION    NOT NULL,
    [VERSION_NO]    BIGINT        CONSTRAINT [DF_T_USER_VERSION_NO] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_T_USER] PRIMARY KEY CLUSTERED ([ID] ASC)
);

